### PR TITLE
Code review for page counter

### PR DESCRIPTION
**Pull request by armantark**
Changes should be selfexplanatory, but @ me in Slack if you need clarification.

### CODE REVIEW

**Comment by ericharding** [comment]
This seems like a pretty complicated change for a relatively small feature.  Could we, instead, treat the page size as 1 when viewing the study?

**Comment by armantark** [comment]
I'd already considered that approach actually. It doesn't seem like a good idea because of the same pagination problem I mentioned before with the whole limiting of results. It has to backtrack exponentially in order to paginate like that, unless I'm understanding it incorrectly. Plus, if we're trying to preserve state in the URL like you said, then doing that would potentially ruin that. I'm not opposed to trying it out, however. But I was mostly concerned with the cleanliness of my changes.

**Comment by ericharding** [comment]
I'm going to dig into this a little further. Something about this doesn't seem right.  I wonder if there's a bug that we're working around that should really just be fixed.

**Comment by armantark** [comment]
Yeah, go ahead. I'm sure my solution isn't the 100% best way to do it.

**Comment by ericharding** [comment]
Alright so I looked a little deeper and I think we can simplify it a lot.

- In the next_study_id function, there is a `recordsTotal` which has the *total* number of records which we don't want because it will be the same forward both the forward and backward search.
- However! we have the `studies` collection which has a count which *is* the value that we need (as long as recordsTotal is <= 1000.)  
- So I think we can just add an index (prev_study count + 1) and a total (prev_study + next_study + 1 or recordsTotal)
- If recordsTotal is > 1000 we could show something like "result 5 / 1000+" but I don't think we need to since we have recordsTotal.  We will still have a problem of paging past the 1k barrier but If you have a workflow with that many studies there are other usability problems we'll hit first.

**Comment by armantark** [comment]
The studies collection is limited by the page_size (so, in most cases it's just 25), unless you want to up that to 1000, in which case it will have to load 1000 studies into memory (in the backend I believe) just to load up the counter index. I don't know if that's a good idea. Plus, even then, you'd have to call the .index function and it'll be linear search time across potentially 1000 elements. I'd actually considered this before, but I didn't think it would work out.

**Comment by ericharding** [comment]
You're right. I should have tested with a larger set.

What if we changed the page size to 100 and showed "100+" for anything with more results than that?  It would still work for anything but the largest workflows.  I think it would be better to have some sort of compromise than adding extra complexity.  We can run this by Willy/Amy and see what they think.

**Comment by williamhoos** [comment]
Eric,

Let's discuss tomorrow. Added comments in slack.

**Comment by ericharding** [comment]
@armantark, could we just return the index as (page_count * page_size) + prev_studies.count + 1?

**Comment by armantark** [comment]
Where does prev_studies come from?

**Comment by ericharding** [comment]
prev_studies is the search results for the previous page.  i.e. the result of search_service.search() with reverse:true.

**Comment by armantark** [comment]
Ohhh, yeah maybe that would be more efficient than doing a linear search. But then again, a linear search over n=25 (or even n=100) is basically instant, so not much to gain. I can do that, though.

**Comment by ericharding** [comment]
It looks like the type-ahead search stuff is in this branch now. Is that intentional?

**Comment by ericharding** [comment]
I just saw your comment on slack.  I guess that the type-ahead work is done in the same branch as the page counter?  Do you think it would be difficult to do an interactive rebase and separate the changes into 2 different branches so we could merge them separately? If that's too much work we can just make sure both features are good and then merge this PR.  In the future, it would be good to create new feature branches off of master for new work.

**Comment by armantark** [comment]
Yeah I don't know what happened. I thought I could just create a new pull request but I was mistaken. We had originally had it on its own branch but I wanted it to have our new changes, so we unwittingly merged it into master thinking it would be fine. I'm not sure if it matters that much though. I'll do it in the future.

**Comment by ericharding** [comment]
Ah, that makes sense. I see how it happened.

**Comment by ericharding** [comment]
Can you give me an update on where this PR is right now? It seems like the autosuggest stuff is still in flux and not ready to be merged yet. Were you able to use my suggestions to simplify the pagination stuff?

**Comment by armantark** [comment]
I thought we decided against simplifying the pagination stuff. Did you still want me to do it? I can. 

Also, yes, Willy wants us to merge it in, even though it's still in flux.

**Comment by ericharding** [comment]
I think if we can reduce it to just a study index and a study count in the graphql it will be much easier to maintain in the future. I think we should definitely do that before we merge this.

**Comment by armantark** [comment]
I'm not sure if we can unless there was some other way that you mentioned that I missed. The counter index is only accurate if the hash is updated properly. We'd have to severely gimp the functionality, otherwise.

**Comment by ericharding** [comment]
So we know how many total results there are. That's in the recordsTotal field.  The hard part is efficiently identifying the position of the current study within the search results?  
I'm fairly sure we can get that data in the study_edge_service.  Where it does a next_study_id(... reverse:true) it shows the studies before this study on the page so we can take that size and add the page count*page size.  Would that work?

**Comment by armantark** [comment]
`next_study_id` does it with the `search_after` option rather than the straight page number option, so it doesn't actually have an inherent page number that it's querying. There's no way to get the page count from search_after besides doing a linear counting, which is obviously not ideal if you're on like page 50. The only way to get the page count is from the search hash, which needs to be properly maintained.

But if you're talking about doing that in order to get the position on that specific page when you DO get the page number from the search hash, then sure, that is definitely doable. It'll remove the requirement of having to do the `index = search_results&.dig(:studies)&.index{ |x| x.id == study[:study][:nct_id] }` line which is O(n).

**Comment by armantark** [comment]
"Pagination of results can be done by using the from and size but the cost becomes prohibitive when the deep pagination is reached. The index.max_result_window which defaults to 10,000 is a safeguard, search requests take heap memory and time proportional to from + size. The Scroll api is recommended for efficient deep scrolling but scroll contexts are costly and it is not recommended to use it for real time user requests. The search_after parameter circumvents this problem by providing a live cursor. The idea is to use the results from the previous page to help the retrieval of the next page."

From the Elastic Search website https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html

**Comment by ericharding** [comment]
You're right.  I think in that case we *should* do the search but put a limit on the number of results.  I.E. if totalResults <= N (where N is probably in the range 100-200) you get an accurate 1/N count otherwise we hide the counter entirely.  This will give us the desired result for most workflows but keep the code simple.

**Comment by armantark** [comment]
Alright, I will get to that today.

**Comment by armantark** [comment]
Wait, so in this case, I don't think we can have the last and first buttons either if we're going to remove the counter when n>200. What should I do?

**Comment by ericharding** [comment]
Could we make a regular search request to get the first/last study when you first navigate to a study?  We could cache the first/last it in the apollo app cache so we don't have to re-request it as you page through studies.  We could use the search hash as a key to invalidate the cache.

**Comment by armantark** [comment]
I mean, it's not a technical challenge, I think, but a matter of ambiguity. A user will see the "last" button when there is no counter and be confused as to what it does and where it takes them, and neither options of either taking you to the actual last or taking you to the "fake" last (i.e. result #200) is optimal. Which leads me to think that maybe I should drop it as well for recordsTotal>200.

**Comment by ericharding** [comment]
the total number of results should always be accurate, right?  That said, I think it would be fine to drop the 'last' when we drop the index.

**Comment by armantark** [comment]
Alright, I'll get to that.

**Comment by armantark** [comment]
@ericharding It should be good to go and working as the way you want. I don't think there are any bugs, but there might be something I missed.

**Pull request merged**
