### PR TITLE
CW-53 - closes 635 - reduce marker font from 21 to 15

### PR DESCRIPTION
**Pull request by williamhoos**
fixes wrapping of 2 digit facility identifiers

### CODE REVIEW

**Review by kaveer-k — CHANGES_REQUESTED** [review]
@williamhoos Thanks for doing this.

I know it is tempting to just make the changes you need and move forward but in general, I think we should start instilling a habit of leaving the code in a better state than we found it so it is easier to maintain going forward (if time allows of course).

In this particular case, we have a lot of repeated code so we should try to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) it up a bit. For example, `MarkerCircle`, `WarningCircle`, `HoverCircle`, and `WarningHoverCircle` all have pretty much the same styling except for the `color` and `border` properties.

We should try to extract out as much common code so we only have to change it in one place. I would recommend creating a `Circle` component:

const Circle = styled.div
  position: absolute;
  left: 0;
  top: 0;
  width: ${K_CIRCLE_SIZE}px;
  height: ${K_CIRCLE_SIZE}px;
  border: 3px solid ${props => props.theme.mapSection.markerBorderColor};
  border-radius: ${K_CIRCLE_SIZE}px;
  background-color: white;
  text-align: center;
  color: ${props => props.theme.mapSection.markerFontColor};
  font-size: 15px;
  font-weight: bold;
  padding: 0;
  cursor: pointer;
  box-shadow: 0 0 0 1px white;
};

And then change each of the specific versions of it to just extend those styles like this:

const WarningCircle = styled(Circle)`
  color: #f6a202;
`;

**Comment by williamhoos** [comment]
agree all of these make sense. I don't have the dev env up and running so try to limit my changes to things with close to 0% chance of breaking or other unintended consequences. I also have no pride of authorship and just made this change because it seemed easier to make the change vs document the request. Happy to have someone take the changes and insert and verify no syntax issues, etc.

**Comment by williamhoos** [comment]
Also, Amy and I were reviewing this and noticed that the facility "Cards" have different size circle/label than the map pins. So looks like another area where the same pattern repeats if we are cleaning structure. Maybe a broader styles clean-up project. Not sure if mapcard and facility card should have same font size (likely) but should certainly have same color scheme.

https://github.com/clinwiki-org/clinwiki/blob/c77b3e1fba66fb67a8dd1e03c875fb9903719f08/front/src/containers/FacilitiesPage/FacilityCard.tsx

**Comment by kaveer-k** [comment]
> agree all of these make sense. I don't have the dev env up and running so try to limit my changes to things with close to 0% chance of breaking or other unintended consequences. I also have no pride of authorship and just made this change because it seemed easier to make the change vs document the request. Happy to have someone take the changes and insert and verify no syntax issues, etc.

Ah got it, thanks for getting back to me on this. Makes sense to limit your changes if you don't have a dev env set up, will keep that in mind when I'm reviewing future PR's from you.

I'll take care of this and make sure the extra cleanup doesn't break anything before we merge into staging.

**Comment by kaveer-k** [comment]
> Also, Amy and I were reviewing this and noticed that the facility "Cards" have different size circle/label than the map pins. So looks like another area where the same pattern repeats if we are cleaning structure. Maybe a broader styles clean-up project. Not sure if mapcard and facility card should have same font size (likely) but should certainly have same color scheme.
> 
> https://github.com/clinwiki-org/clinwiki/blob/c77b3e1fba66fb67a8dd1e03c875fb9903719f08/front/src/containers/FacilitiesPage/FacilityCard.tsx

Yeah I think it's pretty common throughout our code base. I'm all for it if you're okay with prioritizing this.

**Pull request merged**
