### PR TITLE
511 workflow add labels

### PR DESCRIPTION
**Pull request by blatde91**
#511

### CODE REVIEW

**Comment by blatde91** [comment]
bulk update is currently not working, need a way to handle adding when I don't have a singular nctid

also, need to find a way to make the labels update on submit

otherwise, label and facet adding is working as expected

**Comment by williamhoos** [comment]
@blatde91 sorry if it wasn't clear but bulk doesn't need this "add" functionality. We only use bulk for adjusting existing values, so you can just leave it as is as long as bulk still works. To clarify, the labels won't update unless refreshing the page and @ericharding is going to look at updating just this section or just the target facet on save?

**Comment by hifilorau** [comment]
@blatde91 fix the scroll in bulk. Make sure bulk is just styling and then screenshot this bad boy and will approve and put on exp.

**Comment by blatde91** [comment]
Screen Shot 2020-05-01 at 1 35 51 PM

**Pull request merged**
